-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

-- Create plans table
create table public.plans (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text not null,
  type text not null, -- 'wedding', 'fitness', 'home', 'general'
  description text,
  metadata jsonb, -- Store extra details generated by AI
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create tasks table
create table public.tasks (
  id uuid default gen_random_uuid() primary key,
  plan_id uuid references public.plans on delete cascade not null,
  title text not null,
  description text,
  status text default 'pending' check (status in ('pending', 'in_progress', 'completed')),
  priority text default 'medium',
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create plan_context table (chat history / Q&A)
create table public.plan_context (
  id uuid default gen_random_uuid() primary key,
  plan_id uuid references public.plans on delete cascade not null,
  context_data jsonb not null, -- Stores the Q&A history
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.tasks enable row level security;
alter table public.plan_context enable row level security;

-- Profiles policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Plans policies
create policy "Users can view own plans."
  on plans for select
  using ( auth.uid() = user_id );

create policy "Users can insert own plans."
  on plans for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own plans."
  on plans for update
  using ( auth.uid() = user_id );

create policy "Users can delete own plans."
  on plans for delete
  using ( auth.uid() = user_id );

-- Tasks policies (inherit from plan access mostly, but for simplicity direct check)
create policy "Users can view tasks of own plans."
  on tasks for select
  using ( exists ( select 1 from plans where plans.id = tasks.plan_id and plans.user_id = auth.uid() ) );

create policy "Users can insert tasks to own plans."
  on tasks for insert
  with check ( exists ( select 1 from plans where plans.id = tasks.plan_id and plans.user_id = auth.uid() ) );

create policy "Users can update tasks of own plans."
  on tasks for update
  using ( exists ( select 1 from plans where plans.id = tasks.plan_id and plans.user_id = auth.uid() ) );

create policy "Users can delete tasks of own plans."
  on tasks for delete
  using ( exists ( select 1 from plans where plans.id = tasks.plan_id and plans.user_id = auth.uid() ) );

-- Plan Context policies
create policy "Users can view context of own plans."
  on plan_context for select
  using ( exists ( select 1 from plans where plans.id = plan_context.plan_id and plans.user_id = auth.uid() ) );

create policy "Users can insert context to own plans."
  on plan_context for insert
  with check ( exists ( select 1 from plans where plans.id = plan_context.plan_id and plans.user_id = auth.uid() ) );

